### ISSUE TITLE
The test page is not working for me

### ISSUE THREAD

**Issue by jfkthame** [mozilla/emojione-colr#11]
Since I updated to the new EmojiOne release, the test script no longer works (at least for me; maybe it's a local configuration issue?) I don't see any errors in the DevTools console, but clicking Test just doesn't seem to do anything.

@timdream could you look into this, please? Currently, I haven't been able to re-run the test script with the new version of the graphics, so I have only done a superficial visual check that things look OK-ish...

**Comment by timdream** [comment]
@jfkthame Did you re-run `npm install`? See `ccf768a8`.

**Comment by jfkthame** [comment]
I did (and I can see in the console that it's loading resemble.js from node_modules, as expected). But then nothing....

**Comment by jfkthame** [comment]
Ah, got it.... the source SVGs (or at least some of them, I didn't check all) now have 'width' and 'height' attributes, which conflict with the ones added by the test script when rendering the images. Stripping these out of the files fixes the failure.

**Comment by timdream** [comment]
I see. There are still a few image without `width` and `height` attributes.

    $ ls -1 build/colorGlyphs | wc
        1838    1838   24436
    $ grep -rl width build/colorGlyphs/ | wc
        1833    1833   59208

We would have to upgrade the workaround of bug 700533 to something that would check the existence of the attributes...
