### ISSUE TITLE
Can’t get the font to work on Linux

### ISSUE THREAD

**Issue by khaledhosny** [mozilla/emojione-colr#12]
With a simple test like this I always get the emoji shown in a fallback font in Firefox on Linux:

```html
<html>
  <head>
    <meta charset="utf-8"/>
  </head>
  <body>
    <p style="font-family: EmojiOne Mozilla;">🐻</p>
  </body>
</html>
```

I can’t debug this right now, but I suspect this is because the default glyphs are all blank and FontConfig (in its eternal wisdom) ignores blank glyphs in the font and will decide that the font does not support these characters (unless they are characters it thinks can be blank).

**Comment by khaledhosny** [comment]
To test my theory, I manually modified the font and added a dummy shape in all default glyphs and the modified font now shows up as expected.

**Comment by timdream** [comment]
Thanks for filing.

Yes, this is https://bugzilla.mozilla.org/show_bug.cgi?id=1276594. I am closing this as a dup.

**Comment by timdream** [comment]
> I manually modified the font and added a dummy shape in all default glyphs

By "default glyphs", you are referring to manually edit the font and add black-and-white glyphs into the font file? If so it's definitely bug 1276594.

**Comment by khaledhosny** [comment]
Yes, it is the same issue indeed.

**Comment by jfkthame** [comment]
Incidentally (in case this wasn't clear from bug 1276594), this issue shouldn't prevent the font working if loaded remotely via @font-face.... e.g. the test page at https://people.mozilla.org/~jkew/tests/emoji-list.html should work even on Firefox/Linux.

**Comment by khaledhosny** [comment]
This wouldn’t hep me since I’m trying to make it my default emoji font, with FontConfig rules to use it for common emoji fonts so websites using, say, Apple Color Emoji don’t show emoji in black and white from fallback fonts like DejaVu Sans.

**Comment by khaledhosny** [comment]
There seem to be a black and white version of EmojiOne glyphs now: https://github.com/Ranks/emojione/tree/master/assets/fonts#emojione-svg-based-color-fonts
