### ISSUE TITLE
Misencoded emoji in EmojiOne 2.2.1

### ISSUE THREAD

**Issue by dscorbett** [mozilla/emojione-colr#16]
EmojiOne 2.2.1 puts a few emoji at the wrong code points; see Ranks/emojione#258. This is fixed in EmojiOne 2.2.2.

**Comment by timdream** [comment]
Fixed in v0.2.2, 72ea2e4dfd93aaacdf980f92860467b739fb603c .

Will file bug on Gecko to update the file.

**Comment by timdream** [comment]
Thanks for filing the issue!
