### ISSUE TITLE
Add a license to the binary releases

### ISSUE THREAD

**Issue by DeeDeeG** [mozilla/emojione-colr#20]
Hi all,

I am interested in redistributing the binary font from this repo, by including it in a project I am working on.

But it struck me that there is no explicit association of any standard license, licensing terms, etc. to the binary releases.

I feel like to be legally prudent, I need to either direct people to compile the font themselves, or else ask that you kindly add a license of some kind to the binary release.

Thank you for considering.

(Info on the project:

I am writing a simple HTML page that tests browser support for all four OpenType color font formats. It will attempt to load fonts of each format as a locally installed font, and in `@font-face` to simulate usage as a web font. (I will compile and post results for all major browsers on as many platforms as I can get a machine to test on.)

Distributing the source of my test, along with the same fonts files I test with, makes the test 100% inspectable and reproducible.

*As far as I know, this is the only publicly available, open-source COLR/CPAL font.*)

**Comment by timdream** [comment]
Hi. The binary is released under the same term as the source code. There shouldn't be any problems as long as you distribute the binary in the same way as we distribute with Firefox. Please take a look at [LICENSE.md](https://github.com/mozilla/emojione-colr/blob/master/LICENSE.md).

(Disclaimer: I am not a lawyer and this is not a legal advice)

**Comment by DeeDeeG** [comment]
Hi, thanks for the reply.

> (Disclaimer: I am not a lawyer and this is not a legal advice)

I acknowledge you are not a lawyer, and I am not going to take your comments as legal advice.

Just to be super-extra-clear about what you mean:

The license for code, as laid out in [`LICENSE.md`](https://github.com/mozilla/emojione-colr/blob/master/LICENSE.md) says MIT license. So given your comment above and the `LICENSE.md`, it looks like the binary font files are under the MIT license.

Anyways, is it possible to update `LICENSE.md` to more explicitly mention the binary fonts are included under the MIT license? Would you accept a Pull Request that does so?

Otherwise I will just re-distribute the font and point to this thread as how I knew the font files were MIT-licensed.

Thank you once again.
