### ISSUE TITLE
Load eosrei/emojione-color-font as submodule?

### ISSUE THREAD

**Issue by timdream** [mozilla/emojione-colr#4]
It looks odd to me that we are checking in a zip containing all the SVGs. Would it be better if we track the version of the upstream asset by adding the upstream repo as a submodule?

**Comment by jfkthame** [comment]
eosrei/emojione-color-font isn't the real "upstream", it's another downstream consumer. The upstream source of the SVG images is emojione.com, but I don't know if they have a repo we can use in that way; AFAICS, they develop separately, and just post release zipfiles.

I considered pulling the latest release from the web at build time, but I think it's probably better to update manually; any time we get a new version of the source images, we'll want to review the converted font to check that they're surviving the process OK.

**Comment by mikedeboer** [comment]
Official GH repo: https://github.com/Ranks/emojione

**Comment by jfkthame** [comment]
Ah, that's what we should add as a submodule - thanks.

**Comment by jfkthame** [comment]
Hmm, that's an *awfully* big repo to pull in. I think I'd be inclined to stick with just importing their release zipfile.

**Comment by timdream** [comment]
How should we track the version of the zip file, if that's the case?

**Comment by timdream** [comment]
Maybe leave a note like what http://emojione.com/developers/ did ("updated 1-29-16") in the commit log is enough...
