### ISSUE TITLE
consider what font family name we should use

### ISSUE THREAD

**Issue by jfkthame** [mozilla/emojione-colr#7]
I've been building the font with the name "EmojiOne" for now, but I'm not sure that's really a good idea. Given that this will not be a "perfect" conversion of the original EmojiOne graphics -- because there are a few features that are hard to represent precisely in a color-layer font -- and that it's not officially endorsed by the EmojiOne project, it might be better to use a name that clearly identifies our font as a Mozilla derivative.

Note that for our intended use case (bundling with Firefox), the font name will not normally be directly exposed to users, so in that sense it doesn't much matter what we call it. But of course it's possible people will take the font and install it separately for use with other applications, too. That's fine ... but in scenarios like that, I think it's desirable that we have a more distinctive name than plain "EmojiOne". We should leave that name for the EmojiOne project to use themselves for any font products they release, and avoid a potential name clash with our custom derivative.

Some possibilities: "EmojiOne-Moz"? "MozEmojiOne"? "FxEmojiOne"? Something else....?

**Comment by mikedeboer** [comment]
Good call. FWIW, my vote goes to `MozEmojiOne`.

**Comment by mikedeboer** [comment]
But I thought font names are not restricted to one word. If so, I'd like to see `EmojiOne Mozilla`

**Comment by jfkthame** [comment]
Indeed, it wouldn't have to be a single word.
